T_max: 64
ckpt_path: /mount/arbeitsdaten/studenten4/rasoulta/HiVT/checkpoints/HiVT-128/checkpoints/epoch=63-step=411903.ckpt
critic_lr: 0.0001
critic_steps: 1
devices: 1
dropout: 0.1
edge_dim: 2
embed_dim: 128
future_steps: 30
historical_steps: 20
lambda_adv: 0.1
lambda_jerk: 0.05
lambda_r1: 1.0
local_radius: 50
lr: 0.0001
max_epochs: 64
mid_horizon: 20
monitor: val_minFDE
node_dim: 2
num_global_layers: 3
num_heads: 8
num_modes: 6
num_temporal_layers: 4
num_workers: 8
parallel: false
persistent_workers: false
pin_memory: false
root: /mount/studenten/projects/rasoulta/dataset
rotate: true
save_top_k: 5
short_horizon: 10
shuffle: true
train_batch_size: 64
train_gan: true
use_gan: false
val_batch_size: 64
weight_decay: 0.0001
